language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r tests/test_requirements.txt
script: nosetests tests
deploy:
  provider: pypi
  password:
    secure: mvQJBsAUcOnkrbcNryb07uQqhhadG4pRyfiqs+2yEPQDsjksHNoOV2ko3f34AZ9pt0EsUoqHLAI1Lr0VDvAhkpvXp7t1YD8/DAVhUqV3Hzt1v2ithXaG5wDdErDdYPI7tLab9fWs4BgUERqTDvdVP4B5ZFSMzSBOvopL3C7i5KcWwU9dENhEYhMXNkEWvbFRYy81V6lg4oV9w/ktiCORzGtAsAK0LGbzrUclPZ+hbOBqrIXlxnjjto13rjyTQ7CiosxBUu1wNWdEuZTq7W8ipFHynsIOz69r8XS/igJL7aATP4azoPe/mqSEWgC+aPSw0Pz9iOGTJkvkrzyqQJEVy63QmAKQVmIUV2UpzT2r3N4MYxWB4as32nbFoQEUjsNtgyo7Eq0ejzKOF73B5lBYLszDCU118KM/1vyw17CkxsgI+75HgacEHJq0SnEcTaCb/duFLI+AUyvAQS1VWxjpt5rcCA64ZH8nl0yl4JYLW0c/YanuFBYtPSOeK0aTUSDL6ore+7Gy1qDUJAGmYgtHID2aqBBpI7yGBS5A+K6KOe6QPJPZBrmBst+6o6QDndlSxBIOUQv02zA96ANSm52pBSgtdYJZXffrFLcs/O0x78l8E9KT1cBlJzrlN3sOkyMQpFhMVVeOyxQ97B3zR2Q2EaGbTBNQZ3VyAn9uJsIdtX4=
  user:
    secure: jutzZinZ06bRYEEfIJ5RZ1RkFGrkqGAWaUxDkztySxBpAoei2mj01h7sau0urbYTUq/D2qMcVzGZNUbYVL4rZCHhDq8WJqhcTEsfUCsoJoIdi3HyouOnBiPz+A5d+lZO+8Y9nVd8+mPSQ0Q4SJMAb21ryBuwr7B0OEJLqct2RZ34qijoN6cnir6K1+d4OnIs8kh+yJ0MfIx78lohghv+6YIY1hm0/2oaPKZ0jIHOdy4wREuzijfQlDabfBHzKjU+zDUkUBB6sdEcb35iJx3K2qYRh+iS/4v8lQxfg0n4KkfsQ6dAQ1W7loW7QBszTeGvUQXW1HoQ+JfwVbAwYFigR4GwAQkRJSrON40syaOqq9z6kaVAl1ZbVPEFPwim2kobAHFejHWbFurf5VlMetxeVjULWdHqU10fUsazAkVOeKvmjfARe0XUeIlCfhBY1DqN7KMGf3PQgpkHOI3bnymBnFS1gPlF5M1wPtqU5xxjoRMydWPdQJ/Pzone+J436hB8tH8/6uX7rxDeg4e5ihTNbXuEyIHMf+Z4FFG0XtXlGo5esY6Mim+ZHEw6tsg8eFXLmasQGGK65gCx+agu1J+/BNskhBdHmIPrzRceasLAhH5jN7W1mwx6ZQCRvRUHgw++B2MZvg2FfLOjX6g+1YCayCYp37OnghQS9xVM7Rp/JGc=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: U6PnEk2oxNxTQ0ojHCYgHYXhWGm6ETe85uC9Njgq/9BVrTxShGIJi2CVbBSQ6WGhXdgezN/MZqGdigS24o216gTDk+0LR5iI/KBrcSbxeSLf5wq8/exdqxZLNOR82tQQdwMMRGODv0taU3Lyo4MYEcalQbknCguVSQK2Jo7xjyXUYsyjkMWxtYwtCw3kGZvxK0MVJuGkPe+xqyiE9WciQ7fSOYVRAa+tF39rsxd04UQ8XhKHGpkQ98Kf7pwrb8J/orcOqZkPq7QBx1h4PDBMizZquQ7X50+HnRE1pFNnetMnoHcVMPxXZVskHl0rN4jAaEGMjq5enODh7B1C5mMjZNI0Hgyricn6KIwbobj+HirB1RMi9LCn8nLnXfr9fr6MRC+UFDwGObGakS5e3+bI72MudzTWbixb5TN/9K6GbgJrn4cJLxB/nyAQ/yuthHAOb0xUguOBJkJ/2DMAMg0CVxk8ibCfJWjhwm2E32WcUGXCXapg3kVzgl0smbuz5pzKgtkTxYDaPoMzMyw3UZYx81OJWC0jOMZCwKhGS/WidmDAFRw135xrZ3zZW/GyylyVgqrOaXDkZXmpTjkChX7Igwkci50kqtNRy8/XxrjQB5SmYG2BwiXbRLwmuPmS//c1sP23YcwMq27f5tAmzZJ1zy892AVKcgBrN5lLc9cpD1s=
